#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Flipper.Sample.Droid.Resource", IsApplication=true)]

namespace Flipper.Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Flipper.Droid.Resource.Attribute.cardBackgroundColor = global::Flipper.Sample.Droid.Resource.Attribute.cardBackgroundColor;
			global::Flipper.Droid.Resource.Attribute.cardCornerRadius = global::Flipper.Sample.Droid.Resource.Attribute.cardCornerRadius;
			global::Flipper.Droid.Resource.Attribute.cardElevation = global::Flipper.Sample.Droid.Resource.Attribute.cardElevation;
			global::Flipper.Droid.Resource.Attribute.cardMaxElevation = global::Flipper.Sample.Droid.Resource.Attribute.cardMaxElevation;
			global::Flipper.Droid.Resource.Attribute.cardPreventCornerOverlap = global::Flipper.Sample.Droid.Resource.Attribute.cardPreventCornerOverlap;
			global::Flipper.Droid.Resource.Attribute.cardUseCompatPadding = global::Flipper.Sample.Droid.Resource.Attribute.cardUseCompatPadding;
			global::Flipper.Droid.Resource.Attribute.contentPadding = global::Flipper.Sample.Droid.Resource.Attribute.contentPadding;
			global::Flipper.Droid.Resource.Attribute.contentPaddingBottom = global::Flipper.Sample.Droid.Resource.Attribute.contentPaddingBottom;
			global::Flipper.Droid.Resource.Attribute.contentPaddingLeft = global::Flipper.Sample.Droid.Resource.Attribute.contentPaddingLeft;
			global::Flipper.Droid.Resource.Attribute.contentPaddingRight = global::Flipper.Sample.Droid.Resource.Attribute.contentPaddingRight;
			global::Flipper.Droid.Resource.Attribute.contentPaddingTop = global::Flipper.Sample.Droid.Resource.Attribute.contentPaddingTop;
			global::Flipper.Droid.Resource.Color.cardview_dark_background = global::Flipper.Sample.Droid.Resource.Color.cardview_dark_background;
			global::Flipper.Droid.Resource.Color.cardview_light_background = global::Flipper.Sample.Droid.Resource.Color.cardview_light_background;
			global::Flipper.Droid.Resource.Color.cardview_shadow_end_color = global::Flipper.Sample.Droid.Resource.Color.cardview_shadow_end_color;
			global::Flipper.Droid.Resource.Color.cardview_shadow_start_color = global::Flipper.Sample.Droid.Resource.Color.cardview_shadow_start_color;
			global::Flipper.Droid.Resource.Dimension.cardview_compat_inset_shadow = global::Flipper.Sample.Droid.Resource.Dimension.cardview_compat_inset_shadow;
			global::Flipper.Droid.Resource.Dimension.cardview_default_elevation = global::Flipper.Sample.Droid.Resource.Dimension.cardview_default_elevation;
			global::Flipper.Droid.Resource.Dimension.cardview_default_radius = global::Flipper.Sample.Droid.Resource.Dimension.cardview_default_radius;
			global::Flipper.Droid.Resource.Drawable.arrow = global::Flipper.Sample.Droid.Resource.Drawable.arrow;
			global::Flipper.Droid.Resource.String.ApplicationName = global::Flipper.Sample.Droid.Resource.String.ApplicationName;
			global::Flipper.Droid.Resource.String.Hello = global::Flipper.Sample.Droid.Resource.String.Hello;
			global::Flipper.Droid.Resource.String.library_name = global::Flipper.Sample.Droid.Resource.String.library_name;
			global::Flipper.Droid.Resource.Style.CardView = global::Flipper.Sample.Droid.Resource.Style.CardView;
			global::Flipper.Droid.Resource.Style.CardView_Dark = global::Flipper.Sample.Droid.Resource.Style.CardView_Dark;
			global::Flipper.Droid.Resource.Style.CardView_Light = global::Flipper.Sample.Droid.Resource.Style.CardView_Light;
			global::Flipper.Droid.Resource.Styleable.CardView = global::Flipper.Sample.Droid.Resource.Styleable.CardView;
			global::Flipper.Droid.Resource.Styleable.CardView_cardBackgroundColor = global::Flipper.Sample.Droid.Resource.Styleable.CardView_cardBackgroundColor;
			global::Flipper.Droid.Resource.Styleable.CardView_cardCornerRadius = global::Flipper.Sample.Droid.Resource.Styleable.CardView_cardCornerRadius;
			global::Flipper.Droid.Resource.Styleable.CardView_cardElevation = global::Flipper.Sample.Droid.Resource.Styleable.CardView_cardElevation;
			global::Flipper.Droid.Resource.Styleable.CardView_cardMaxElevation = global::Flipper.Sample.Droid.Resource.Styleable.CardView_cardMaxElevation;
			global::Flipper.Droid.Resource.Styleable.CardView_cardPreventCornerOverlap = global::Flipper.Sample.Droid.Resource.Styleable.CardView_cardPreventCornerOverlap;
			global::Flipper.Droid.Resource.Styleable.CardView_cardUseCompatPadding = global::Flipper.Sample.Droid.Resource.Styleable.CardView_cardUseCompatPadding;
			global::Flipper.Droid.Resource.Styleable.CardView_contentPadding = global::Flipper.Sample.Droid.Resource.Styleable.CardView_contentPadding;
			global::Flipper.Droid.Resource.Styleable.CardView_contentPaddingBottom = global::Flipper.Sample.Droid.Resource.Styleable.CardView_contentPaddingBottom;
			global::Flipper.Droid.Resource.Styleable.CardView_contentPaddingLeft = global::Flipper.Sample.Droid.Resource.Styleable.CardView_contentPaddingLeft;
			global::Flipper.Droid.Resource.Styleable.CardView_contentPaddingRight = global::Flipper.Sample.Droid.Resource.Styleable.CardView_contentPaddingRight;
			global::Flipper.Droid.Resource.Styleable.CardView_contentPaddingTop = global::Flipper.Sample.Droid.Resource.Styleable.CardView_contentPaddingTop;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Flipper.Sample.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Flipper.Sample.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
